return {
  'smiteshp/nvim-navic',
  opts = {
    highlight = false,
    separator = " ❯ ",
    depth_limit = 0,
    depth_limit_indicator = "..",
    safe_output = true,
    icons = {
      File = "󰈙 ",
      Package = ' ',
      Module = " ",
      Namespace = ' ',
      Key = "󰌋 ",
      Operator = "󰆕 ",
      Null = ' ',
      Boolean = ' ',
      Number = "󰎠 ",
      String = ' ',
      Variable = "󰂡 ",
      Constant = "󰏿 ",
      Function = "󰊕 ",
      Array = ' ',
      Object = ' ',
      Enum = " ",
      EnumMember = " ",
      Struct = "󰠲 ",
      Class = "󰠱 ",
      Interface = " ",
      Field = " ",
      Property = "󰜢 ",
      Constructor = "󰛄 ",
      Method = ' ',
      Event = " ",
      TypeParameter = "󰅲 ",
    },
  },
}
